Government::NewsArticle.create(
  :group => 'events',
  :en_headline => "New High-Speed Rail to Open",
  :en_summary => "A new high-speed railway, the republic’s first, is scheduled to open for public use by the end of the month. This line, likely to be the first of many to come, will connect Ríga, Novegráde Velíkei, and Néugrade.",
  :en_article => "<p>The first line of the the nation's first highspeed rail is scheduled to open by the end of the month.</p>\n<p>The rail, operated by Źelnóusko (ŹPNS), will connect Ríga, Pleskóve, Novegráde Velíkei, and Néugrade. It has already gained the popular nickname \"Źapenése\", a slurred reading of the acronym ŹPNS.</p>\n<p>The new ŹPNS rail is often viewed as a sign of Novegrad coming into the modern technological era. Highspeed rails such as France's TGV have been in use in Western Europe for a number of years, but the ŹPNS is the first in Eastern Europe. If it is successful, construction on several new lines may begin as early as next year with the help of government funds.</p>\n<p>The highspeed lines for the most part share the same stations as traditional railroads, although they have their own dedicated tracks, and will only stop at major cities and not towns in between. This will allow the trains to travel at speeds of 320kph commercially.</p>\n<p>The President has personally requested to be on the maiden run as he returns to Novegráde Velíkei after a scheduled meeting with the governor of Neugradeskáia Oblost.</p>",
  :nv_headline => "Оскриет нове скоросне желѣзопанти",
  :nv_summary => "Новей скоросней желѣзопанти-то, пирвей республикѣ, планене ест оскрити публицностюм ко конецем мѣшиѕи. Ша линя, вѣраетно пирвая зе многе, суеғьет гради Рига, Новеграде и Неуграде.",
  :nv_article => "<p>Пирвая линя-та пирва скоросна желѣзопанти странѣ ест планене оскрити ко конецем мѣшиѕи.</p>\n<p>Инденей Желноуском (ЖПНС) желѣзопанти-то суеғьет Ригу, Плесков, Новеград Великий и Неуград. Ож називати популарной кликой „Жапенесе‟, недовѣдомом вуирѣцем акронима ЖПНС.</p>\n<p>Новий желѣзопанти-то ЖПНС цестѣ соцедовати знакем тово-це Новеграде воходит во соврѣменнун технољогицескун вѣкен. Скоросние линѣ, акоже ТГВ на Вранци, тилизовасци ож сколицестуо астоу на западнѣѣм Еуропѣ, но ЖПНС ше-и пирвием на востоцнѣѣм. Анно вуиконцит оспѣха, может наценати строенье нѣкотрих новоу линёу ценайсо наступном астом при помогьи сударестуенна винансированьа.</p>\n<p>Скоросние линѣ-ти болшей цестюм отиѣздат од ших сам стаци, како традицни трени, но ѣздат по вуидѣленѣх слѣдѣх и толкѣ бадут постауловатиш о глаун град, а не о видор град вмести них. Ше розрѣжаст то-це трени-ти можут ѣздит по торговой скоростюм 320км/п.</p>\n<p>Президенте-те саме попрожиле то-це он сомогле би шѣсти на пирвѣ ѣздѣ, када оне завратити шебе во Новеграден Великуюн за планеном зашѣденьем со владителем Неуградескоей обл.</p>"
)
Government::NewsArticle.create(
  :group => 'events',
  :en_headline => "Syktyvkar Prepares for Local Elections",
  :en_summary => "Syktyvkar, the capital of the Komi Republic, will hold elections in three days. The mayoral and city council races are being watched by the entire country after the former mayor was ousted and imprisoned on charges of corruption.",
  :en_article => "<p>In three days Syktyvkar, capital of the Komi Republic, will hold city elections. The mayoral and city council races are being watched by the whole country after the former mayor was arrested on charges of corruption.</p>\n<p>The former mayor, Izö Śéleskei, was removed from office and imprisoned two months ago after being convicted of corruption. Records indicate that he has both accepted bribes from a number of businesses in exchange for his support on policies, and large sums of money from local criminal organizations in exchange for impunity. This information came to light after an unidentified informant leaked directly to office of the governor and to the local media, creating a scandal that caught the attention of the entire nation. Śéleskei is currently serving ten years in prison.</p>\n<p>The scandal has almost completely destroyed the Syktyvkar branch of the Labor Party, leaving the next election nearly impossible to predict. The entire country will be watching the election results as the Center, Progressive/Social Democratic Alliance, and Komi Order parties struggle for dominance in the city, which has been almost completely controlled by the Labor Party since 1991.</p>",
  :nv_headline => "Сихтикаре годовици ко мѣснами вуиборам",
  :nv_summary => "Сихтикарѣ-те, столица республикѣ Коми, бадут трес три дена вуибори. Мотрит плона страна камнанѣ-те за главой со редой градеуниеми за неж буиваљна глава буила сосадена со власти и заклуѕана, буиве овинена во корупси.",
  :nv_article => "<p>Трес три дена во Сихтикарѣ (Сыктывкаре), столица республикѣ Коми, бадут градеуние вуибори-ти. Мотрени есат кампанѣ за градеуной главой со градеуной радой на плоной страной, за неж буиваљна глава буила сосадена со власти и заклуѕана, буиве овинена во корупси.</p>\n<p>Буиваљная глава-та, Изӧ Шелескей, буила сосадена со власти и заклуѕана дова мѣшиѕи созада, за неж буила овинена во корупси. Документи показовати то-це оне приймѣле и позплати зе некотрѣе компанёу за ево глас политикам, и болиши суми рагѣ за бескараљности од мѣсон преступон организаси. Вуиявилашин ша инвормася-та за неж неросзнаме инворматнике росказале премѣ ко конслем владитела и ко мѣсной медей, туорекьое скандаљ, котре овратиле пожер кѣлѣ странѣ. Шелескей-ёт во стоекьо врѣмено шѣдит турмѣ дешити азот.</p>\n<p>Ше скандаље соружиле мало до плоности сихтикареску вѣтуа Партин Труда, оставин наступни вуибори-ти тѣм-како неможене предвидѣти ресуљтат. Кѣла страна бадет мотрѣти ресуљтати вуибор, еда бориш Партя Центара, союсе Предевих со Соцял-Демокрадицескиеми, и Ордене Коми за владу во градѣ, котре буиле совим под Партей Труда со 1991 асту.</p>"
)
Government::NewsArticle.create(
  :group => 'news',
  :en_headline => "2010 Military Spending Increase",
  :en_summary => "In wake of recent events and aging equipment, the Veche has increased military spending for 2010. This funding will, among other things, expand the Northern and Baltic fleets and replace aging air force planes with the most modern equipment available.",
  :en_article => "<p>The Veche and the Council of Nations have recently approved an addendum to the Fiscal 2010 Budget allowing a 58% increase to military spending allowing for the modernization of the armed forces.</p>\n<p>This plan would increase total spending to 140 billion marks (30 billion USD), up 52.6 billion marks from last year. Most of this money is to be directed toward replacing aging equipment, particularly in the navy and air force. Although exact amounts are not yet decided, this increased spending is likely to continue for several years.</p>\n<p>Increasing tensions in the Middle East and elsewhere have caused concern in the Novegradian government for the security of the nation and its allies and for Novegradian citizens worldwide. The unexpected mid-flight failure of an Le-04 Fighter last October that forced it into an emergency landing in the Mediterranean Sea near Crete has helped to expedite the passage of this bill.</p>\n<p>A large portion of this year's as well as coming years' funds are directed toward the refurbishing of the Northern Fleet. Construction of a new Cernovolk-class aircraft carrier has already begun in Śěveromorijá with plans for a second and a Riga-class nuclear submarine in Onéźeske. Both of these designs are the most modern designs available to the Novegradian military. An undisclosed number of new Le-11 fighters have been ordered as well.</p>\n<p>Which ships and planes are to be decommissioned has yet to be announced. India and South Korea have both agreed to purchase several destroyers and Le-06 fighters.</p>\n<p>An additional 52 billion marks (11 billion USD) has been set aside to be distributed over the next three years for renovating and modernizing naval bases in Murmáne, Arhánjeiske, Ríga, and Libáva.</p>\n<p>Minister of Defense Konstantíne Vladínovice Moskóvine has said that the number of active military personnel is not expected to increase significantly over the next few years barring unforeseen circumstances.</p>",
  :nv_headline => "Милитарни наклади 2010 а. овелицаци",
  :nv_summary => "За недамен пробуикь со нарадиям старекьами, Вѣце овелицовале мититарние наклади-ти на 2010 асто. Ше винансированье бадет зашиловати Шѣверний хлот со Варижескием премѣньати старекьи военно-воздушни самоледи нарадиям соврѣменншами дошигами.",
  :nv_article => "<p>Недамно затуердилѣ Вѣкье со Собраньем Народ додани-те во накладѣх хинансова асту 2008, котре овелицит на 58% милитарни наклади и розрѣжит модернизацю науружен шил.</p>\n<p>Ше плане-те овелицоваст кѣлу суму наклад до 140 билён марек (30 билён американезок доллар), 52.6 билён марек болше, неж во прошло асто. Вѣѕина рагек бадет проведена ко премѣненьем старекь нарадий, глауно во шилах военно-морескѣх со военно-воздушниеми. Колиже пунтша сума егье не рѣшена, ши овелицени наклади вѣраетно простануци нѣкотроу астоу.</p>\n<p>Шилима тягности Близѣѣм востокѣ и видорѣх мѣстѣз прицинаст беспогой вонутри новеградескаево правястўу од охронѣ народа, алянекь и новеграгьѣнь по кѣломировием. Нецеганая авариньа-та по полетем истребита Ле-04 прошлу румѣну, котрая прицинила аварином пошѣдем во Срѣдижемескѣѣм морѣ па Критѣ, ша помагла затуерденье скорити шево законопроехта.</p>\n<p>Болиша цести наклад шево асту тож со наступниеми проводацин ко подноуленьем Шѣвернаево хлота-то. Строенье-те нова авияноса класа „Церновелке“ ож нашналеш Шѣверомориях со планам другаево и идровѣ подводнѣе класа „Рига“ Онежескѣ. Оба зе ших - соврѣменншами планам, дошигамами новеградескием милитарем. Тож креналошин нерозкрито сколицестуо новоу истребитеу Ле-11.</p>\n<p>Егье не ояулено, котри вѣни со самоледам сопихьуцин. Индия со Лѣтной Кореёй обѣ соглажилѣш кренати нѣкотроу миноносеу с истребитам Ле-06.</p>\n<p>Егье 52 билёна наздадомих марек-то (11 билён ам. доллар) отложилошин со тѣм-це роздадицин за наступна три асту деля подноуленьа со модернизацин морезок баз во Мурманѣ, Арханьейскѣ, Ригѣ и Либавѣ.</p>\n<p>Министере Обранѣ Константине Владиновице Московине сорѣѕиле то-це сколицестуо ахтивних военних не цегасцин знацимѣ овелицоватиш за наступноу нѣколке астоу, оклуѕаен нецегани находи.</p>"
)
Government::NewsArticle.create(
  :group => 'news',
  :en_headline => "Floods Recede as Baltic Storm Breaks Apart",
  :en_summary => "Floods along the Baltic shoreline subside after nearly a week as the recent Baltic cyclone begins to weaken. Floods have caused significant damage in Ríga and Révele while hurricane-force winds pounded Tórge and Néugrade.",
  :en_article => "<p>Floods along the eastern shore of the Baltic Sea are finally beginning to recede after nearly a week as the most recent Baltic cyclone \"Jothan\" dissipates.</p>\n<p>Jothan is responsible for 17 deaths in Novegrad and 78 across Europe, and billions of dollars of damage. Around the Baltic Sea it caused storm surges of up to five meters, flooding numerous coastal cities, including large parts of Néugrade, Pernáu, Ríga, and Libáva. Powerful waves and winds were responsible for destroying a part of the unfinished Kotlíno dam across the Nevá Bay, which upon its completion was supposed to protect Néugrade from such surges. Construction is believed to have been set back approximately 15 months.</p>\n<p>Much of downtown Ríga and Pernáu experienced flooding that lasted for up to three days. These cities are quickly returning to life as work crews move in to clear the streets and repair damaged structures. Many schools and other businesses will remain closed until water damage is repaired and their buildings are declared safe.</p>\n<p>Most sea-going vessels on the Baltic Sea had safely returned to port thanks to warnings received from Western Europe. Many boats were sent upriver temporarily, and many of those that remained in harbors open to the sea suffered significant damage. Naval vessels were all rebased into the sheltered harbors of Lake Kiśezerse (Ķīšezers) near Ríga and Lake Libáva near Libáva, both protected from storm surges. Elsewhere, hurricane-force winds did significant damage as well.</p>\n<p>Jothan was an unusually powerful European wind storm, or \"orkan\". It originated near Newfoundland before traveling across the Atlantic, picking up strength, before striking England, Denmark, and Germany directly and then moving into the Baltic Sea. Now weakened, the remains of the storm are expected to cause heavy snowfall in Karelia and Śěverno-Duineskáia Oblost.</p>",
  :nv_headline => "Вода сопадаст на то-це варижеска буря тишици",
  :nv_summary => "Розливи-ти по вием берегѣ варижескѣ тобирво отливати за мало шемицой на то-це недамне циклоне нацинаст бесшиловатиш. Ти содали многознацено сколицестуо повреденьа во Ригѣ со Ревелем еда напускаеш на Торген со Неуградем вѣтри со шилой ураганеской.",
  :nv_article => "<p>Розливи-ти по востоцнѣ берегѣ Варижескаево мора во конецѣ наценатиш отливати за мало шемицой на то-цу недамне циклоне „Ётан“ бесшиловасци.</p>\n<p>„Ётане“-те приѕиной 17 смортей на Новеградѣ и 78 погољом Еуропѣ, и билёни доллареу повреденьек. При Варижескѣѣм морѣ прициниле буряни бушкољи со вуизотой до петех метер, розливакьие многе побрѣжноу градеу и воклуѕаен болши цестие Неуграда, Пернава, Ригѣ и Либавѣ. Шилни волни со вѣтрам буили приѕиной соруженьа цести незаконцена Котлинескавео тама трес Неускаево залива, котре по суоем настроеньѣ надо буиле би Неуграде охраньати од бушкољ тад. Муислат то-це строенье е застаулене огољо 15 мѣшиѕей.</p>\n<p>Буили во многе цестеу города Ригѣ со Пернавем розливи, простанакьиш до трех дена. Ши гради буистрѣ шибѣ вратита житени, еда приходин рабокьи бригади оцишкьат олики и репарат повредени будови. Многе школоу со бизнесам видорами побадут затулидиеми до врѣмен, еда повреденье водой отрепарасцин и суои будови оявасцин бесобасениеми.</p>\n<p>Вѣѕина мореходноу вѣноу Варижескѣѣм морѣ завратила в охронѣ на портени, аття приймѣнами од Западнѣе Еуропѣ презказаньам. Многе вѣноу послалишин ивени на врѣмено, и мнгое остауленовево в оскритѣх морем ғаменѣх знацимѣ повредилишин. Вие военно-морески вѣни премѣстовалишин во прикритони ғаменони ежера Кишезерсе (Кīшезерс) близе Ригѣ и ежера Либава (Лийпāја) близе Либавѣ, обѣ охранени од бушкољ. Мѣстѣх видорѣх вѣтри с ураганеской шилой тож содали многе повреденьек.</p>\n<p>„Ётане“-те буиле невобуиѕайнѣ вайговом орканем. Нашналеш близе Новѣе Хундлѣндиѣ пред, неж прешѣгле трес Атлантицескаево океяна и обиле Англию, Дони и Германю и задѣм прошеле трес Варижескаево мора. Тобирво безшиливеш, цегати то-це слѣди прицинати шилне снѣгопад Карели со Шѣверно-Дуинескоюн облостюм.</p>"
)
Government::NewsArticle.create(
  :group => 'news',
  :en_headline => "President in Moscow for Russian Oil Talks",
  :en_summary => "President Mihajíle Pétrou is in Moscow this week for a series of talks regarding the price of Russian oil and natural gas sold to Novegrad and transit costs for using Novegradian pipelines. Pétrou is confident that an amicable resolution may be agreed upon by next week.",
  :en_article => "<p>President Mihajíle Pétrou is meeting with Russian President Dmitry Anatolyevich Medvedev and several oil executives in Moscow this week for a series of discussions regarding the petroleum market and the price of natural gas and oil purchased from the Russian Federation.</p>\n<p>Russia is one of the world's leading producers of natural gas, and Europe's primary supplier. Over the last few years it has gotten into a number of disputes with neighboring nations, while demanding higher prices, closer to the standard market rates. This culminated in Russia shutting off gas supplies to the Ukraine on January 1, 2006 for several days, sending a ripple effect across Europe.</p>\n<p>The exact nature of the agreement that Pétrou is prepared to offer regarding the sale of Russian natural gas to Novegrad is not yet known. Many analysts are predicting an increase in rates, though lower than Russias demands, likely in exchange for something. Transit costs through Novegradian pipelines may be a bargaining point.</p>\n<p>Russia and Novegrad's shares in the European oil market are likely to be discussed as well. Both are major oil producers, though Novegradian oil must pass through Prussia to reach mainland Europe, and through Russia to be sent anywhere else.</p>",
  :nv_headline => "Президенте во Москеве за преговор о рошзийскѣ нехтѣ",
  :nv_summary => "Президенте Михаиле Петров-от во Москеве ест шу шемицу за реду преговор, казакьши ко кѣной нехтѣ со жемном газем рошзийзок торган Новеградем и ко кѣнам проѣзда по новеградескѣх нехтоводѣх. Ест ците во том-це дружеске рѣженье можеби соверване ко наступной шемицой.",
  :nv_article => "<p>Преденте Михаиле Петров-от вастаст шу шемицу со рошзийскием президентем Дмитрие Анатолиевиче Медведеве со нѣколке главоу нехтѣ во Москеве за реду преговор, казакьши марнатем со кѣной жемна газа со нехтѣ, креновинаево зе Рошзийскѣе Хедерасин.</p>\n<p>Рошзия-та ест едной зе векье вуидакь вуитуорител жемна газа мирѣ и ест глаунейшем давателем Еуропой. Трес нѣкотрѣе прошлоу астоу буиле во нѣкотроу спороу со сужѣднами странам, вуипуидаен кѣни вуихьи, ближи ко марнатами стандартам. Ше дошегло найвуихьее еда Рошзия затуливала остеѕень газа Окраинун пирвий во ледану 2006 а. на нѣкотроу денеу, вуисилакьое волнове евехте виғу Еуропун.</p>\n<p>Пунтше естестуо соглаженьа-то, котре Петроу годове предлежити, казагьаевош продагьой рошзийска жемна газа Новеградем, егье не вѣна. Многе аналитицеу предвигьат то-це стандарти овелицаци, но дов уравеньи нижна сотреби Рошзиѣ, вѣраетно за цеш. Кѣни-ти проѣзда можебу пунтем преговорѣх.</p>\n<p>Юкани Рошзиѣ и Новеграда во марнатѣ еуробейскѣ нехтѣ тож вѣраетно прешун прешунацин. Оба - глаунами вуитуорителам нехтѣ-те, но тово новеградеско надо би просилацин трес Рошзиѣ со тѣм-це солецин кудиш видорунево.</p>"
)
Government::NewsArticle.create(
  :group => 'news',
  :en_headline => "Tórge and Néugrade Airports Reopen After Storm",
  :en_summary => "Tórge and Néugrade International Airports have reopened today on a limited schedule after being closed for four days due to wind and ice damage caused by the Baltic cyclone. Service to several major cities has been restored, and full service should be operational within a week as damaged terminals are repaired and runways cleared of debris.",
  :en_article => "<p>Tórge and Néugrade International Airports, as well as several other regional airports, have reopened today after having been closed for four days due to the Baltic wind storm \"Jothan\".</p>\n<p>The airports are now operating on a limited schedule with service restored to several major cities. However, repairs will continue on the airport grounds through next week.</p>\n<p>They were originally closed because of high winds and ice storms caused by the cyclone, which grounded traffic, damaged terminals and airplanes, and threw debris all over the runways. As airplanes and runways are being de-iced, full service should begin to return. In the meantime, several terminals remain closed because of wind damage, debris-covered roads, and damaged airplanes.</p>\n<p>Full service should return by next week.</p>",
  :nv_headline => "Еропорте Торгескей со Неуградескием оскривата вноу за бурей",
  :nv_summary => "Вмеснародней Еропорте-те Торгескей со Неуградескием шеден оскривалѣ вноу по менишами порам за неж затулилѣшин на цетире дена про соданом на варижеском циклонем повреденьем од вѣтра со ледем. Полети нашнали ко некотрием глауноу градеу, и вие полети надо бу займѣёватишин трес шемицу еда повредени термали отрепаратишин и олетно-прилетни драги оцистацин од розброса.",
  :nv_article => "<p>Вмеснародней Еропорте-те Торгескей со Неуградескием, тож со нѣкотриеми раённоу еропортеу видороу, шеден оскривали вноу за неж затулилѣшин на цетире дена про варижеском орканем „Ётан“.</p>\n<p>Соѕаса есат открити по менишами порам и полети завратилишин нѣкотронево глауноу градеу. Колиж ест, репарацѣ бадет простатиш на еропортескѣх вокрагѣх до наступнѣ шемицѣ.</p>\n<p>Ех затулили наѕално про бушковам со ледем, прициненами на циклонем, котри остауловали самоледи на зень, поврегьали терминали со самоледам и брозали розброс по вие ОПД. Еда кулишин лед со повоз и ОПД, вие ослуги надо бу наценати вратитишин. На врѣмено нѣкотровево терминалеу-то егье бадут затулити про повреденьем од вѣтра, критами на розбросем драгам и повреденами самоледам.</p>\n<p>Вие полети надо бу завратацин ко наступной шемицой.</p>"
)
Government::NewsArticle.create(
  :group => 'news',
  :en_headline => "Veche Approves New Factory Pollution Restrictions",
  :en_summary => "The Veche has approved a new bill calling for stricter factory pollution control. Many older factories continue to operate in the north and east of the country at levels the World Health Organization considers \"unacceptable\".",
  :en_article => "<p>The Veche has approved a bill calling for stricter factory pollution control. This has largely been in response to the slow process of change thus far seen in many of the industrial cities of the north and east of Novegrad.</p>\n<p>These new regulations will introduce more active inspection and harsher penalties for factories that have failed to comply with stipulated protocols. Some of the worst-affected cities may be receiving government assistance for upgrading facilities.</p>\n<p>In the Soviet era, many factories were built across the country under fairly lax regulatory restrictions. In many of the western provinces these have since been replaced or upgraded thanks to new prosperity and investments from western Europe, as well as a general desire to meet Western standards of cleanliness and pollution control. In the northern and eastern provinces, however, these positive influences have been slower to develop. In smaller towns especially, many factories continue to by and large avoid active regulation and inspection.</p>\n<p>In some industrial areas air pollution has reached hazardous levels. Many people have taken to wearing breathing masks over their mouth and nose in cities such as Tázkare and Suětlogóreske, though a lifetime living in these conditions nevertheless has its impact on health.</p>\n<p>Another bill concerning funding for environmental clean-up in some of these areas is due to be introduced in the near future.</p>",
  :nv_headline => "Вѣкье затуердиле нови рестриксѣ, казакьиш ексалатам зе завод",
  :nv_summary => "Вѣкье затуердиле нов законопроехте, котре вуипуитоваст тажу надинду над заводнами ексалатам. Многе староу заводеу на шѣверѣ со востокем странѣ егье вуитуороватиш нав уравеньих, котрие соцедоваст неприймѣемами Кѣломирове организася стравиёохронѣ.",
  :nv_article => "<p>Вѣкье затуердиле законопроехт-от, котрей вуипуитоваст тажу надинду над заводнами ексалатам. Великой мѣрой ше осдает за мудном процесом осуѣшеньа до стоекьа дена во многе промуислевоу градеу на шѣверѣ со востокем Новеграда.</p>\n<p>Ши новие презписи-ти воведут вон утребленьен векье дѣлакьа надиндок со тажей кажнюм деля неблудакь сотребни правигла завод. Нѣкотрие зе град-то хужих виех по заводнѣ ексалатѣ можебу станут приймѣякьием сударистуонн залог деля подноуленьа комплекес.</p>\n<p>При Совѣтескѣѣм вѣкѣ многе заводеу-то забудовалишин погољом странѣ под домѣрнѣ леғками презпизам со рестриксям. На вѣѕинѣ западен облостей, то ож подновили или премѣнили новами комплексам со ших врѣмен про новом сбожиям со вложеньем од западнѣ Еуропѣ, и тако и новой обекьой волей деля равенности ко западнами стандартам цистотѣ с омѣреньем забреденьа. Колиж ест, на шѣвернѣх со востоцниеми облостих егье несат скѣла росуити ши добри овливаньи. Глаунѣ во менишѣх градикѣх, заводи простануци вуитуоровати, оходи надинду со презпизаньем цести.</p>\n<p>Во нѣкотрѣѣм промуислевоу раёнеу, ексалате ож достубиле дов обасен оравеньей. Многие тобирво рават ношит санитарни маски со тѣм-це закривати суои рот со носем, во градѣх, акоже Тазкарѣ со Суѣтлогорескем, но виғож прожити виға житени при тадѣх станѣх – ше худѣ овливаст стравия.</p>\n<p>Видорей проехте-те, казакьейши ко винансированьем деля поцистеньа на нѣкотрѣѣм ших раёнеу вокражненьа, ше во блиғьѣ наступнѣѣм должене воводицин.</p>"
)
Government::NewsArticle.create(
  :group => 'news',
  :en_headline => "Karelia Launches New Language Education Program",
  :en_summary => "The Karelian Ministry of Education has launched a new program aimed at promoting use and comprehension of the Karelian language. Beginning this coming year, it aims to combat the low proficiency rates in Karelian seen in most of the population and the perception of it not being suitable for many modern-day uses.",
  :en_article => "<p>The Karelian Ministry of Education has launched a new program aimed at promoting use and comprehension of the Karelian language. This program will increase funding for Karelian language curricula in primary and secondary schools. Within five years it hopes to see mandatory basic courses on Karelian in all primary schools, as well as optional more advanced classes offered in Karelian as well as Novegradian.</p>\n<p>Out of the five republics within Novegrad, Karelia has the lowest usage rate of its national language. Only about 7% of the population use Karelian as their primary language, and only 24% of the entire population can claim fluency. Many of these speakers know Finnish as well, and may revert to Finnish whenever they come across a topic they are not as comfortable dealing with in Karelian.</p>\n<p>The Karelian language is still battling a stigma of being an uneducated language not fit for many modern-day uses. Today the majority of Karelian speakers live in the countryside, while Finnish and Novegradian dominate cultural and intellectual life in the cities. While quite a few people may use Karelian for daily-to-day matters in the home, few prefer it in business or educational settings.</p>\n<p>Currently many schools have optional Karelian language courses, though relatively few offer classes in Karelian beyond primary school.</p>\n<p>The Ministry of Education has been working with the Ministry of Culture and various other groups and hopes to see more widespread comprehension, usage, and acceptance of Karelian throughout the Karelian Republic.</p>",
  :nv_headline => "Кареля овегла нову кампаню лизигева науѕеньа",
  :nv_summary => "Карелеское Министерестуо Науѕеньа овегло новаю кампаню-то, котрая нацегаст подвод рѣѕеньа со довѣстюм карелескаево лизика. Нацинаен со наступна асту, КМН хокьет загнати ниски мѣри омѣньа ко карелескием лизикем, находени вѣѕинѣ нашељеньа и надвид тово-це карелескей нет годне ко многе соврѣменноу отребленьеу.",
  :nv_article => "<p>Карелеское Министерестуо Науѕеньа овегло новаю кампаню-то, котрая нацегаст подвод рѣѕеньа со довѣстюм карелескаево лизика. Ша кампаня наздаст на винансированьен деля озновѣ науѕеньа карелескаево лизика во школах наѕалнѣх со срѣдниеми. КМН надѣеци на то-це трес пети азот бадут преважние коренние ороки-ти по карелескѣѣм лизикѣ во виех наѕалнѣх школах, тож со вуихьами орогам поволи, предлежимами и накарелескѣ и нановеградескѣ.</p>\n<p>Зе петех аутономен республик, наставекь Республикой Новеградескоюн, на Карели-то найнижне держекьо нарорде лизик сколицестуо нашељеньа посту. Толкѣ %7-то говорит накарелескѣ в акостуѣ глауна лизика, и толкѣ %24-то зе кѣла нашељеньа говорит суѣбоднѣ. Многие зе ших рѣѕител тож держат сумеский лизик, и цестѣ преходат на сумескуюн, када находат тему, о котрѣѣм име нет абро прешунити накарелескѣ.</p>\n<p>Болѣзни егье лежит на карелескѣѣм лизикѣ-те о том-це ше лизике нет годне ко соврѣменном отилизновиньем. Нинѣ вѣѕина рѣѕителеу по карелескѣѣм лизикен живет за градам, а сумеские и новеградеские лизики – прѣважни во житени и куљтурнѣ и интелехтуаљнѣ во градѣх. Колиже домѣрнѣ грамадно сколицестуо лудеу тилизоваст карелеский лизик-от деля кожноденев дѣл во домѣ, малокето волит во вокражненьѣх бизнеса или науѕеньа.</p>\n<p>Нинѣ во многе школоу есат ороки-ти по карелескѣѣм лизикѣ поволи, но малокотрие предлежат орокеу зав оконценьа наѕална школѣ.</p>\n<p>Министерестуо-то Науѕеньа работаст вместе со Министерестуом Куљтурѣ со нееднами видорами организазям, и надѣеци на то-це прохираци довѣсти, отилизновинье и лижости карелескаево лизика па вех Республикун Карелескуюн.</p>"
)
